name: esports_manager
description: Esports Tournament Management Platform
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true



# name: esports_manager
# description: Esports Tournament Management Platform
# publish_to: 'none'

# version: 1.0.0+1

# environment:
#   sdk: '>=3.0.0 <4.0.0'

# dependencies:
#   flutter:
#     sdk: flutter
#   supabase_flutter: ^2.3.4
#   shimmer: ^3.0.0      # For loading skeletons
#   google_fonts: ^6.0.0 # For Anton & Poppins fonts

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^3.0.0

# flutter:
#   uses-material-design: true

#   fonts:
#     - family: Anton
#       fonts:
#         - asset: assets/fonts/Anton-Regular.ttf
#     - family: Poppins
#       fonts:
#         - asset: assets/fonts/Poppins-Regular.ttf
#         - asset: assets/fonts/Poppins-Bold.ttf
#           weight: 700

#   assets:
#     - assets/fonts/
